{{ if .Values.jenkins.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-jenkins-settings
  labels:
    app: {{ template "fullname" . }}
data:
  settings.xml: |-
    <?xml version='1.0' encoding='UTF-8'?>
    <settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns="http://maven.apache.org/SETTINGS/1.0.0"
              xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                          https://maven.apache.org/xsd/settings-1.0.0.xsd">
        <localRepository>/var/jenkins_home/.m2/repository</localRepository>
        <servers>
            <server>
                <id>nexus-releases</id>
                <username>admin</username>
                <password>admin123</password>
            </server>
            <server>
                <id>nexus-snapshots</id>
                <username>admin</username>
                <password>admin123</password>
            </server>
        </servers>
    </settings>
{{ end -}}
