dependencies:
- name: docker-registry
  version: 1.2.1
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: jenkins
  version: 0.16.0
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: sonatype-nexus
  version: 1.1.1
  repository: https://kubernetes-charts.storage.googleapis.com/
