jenkins:
  enabled: true
  Master:
    Image: jenkins/jenkins
    ImageTag: alpine
    ServiceType: NodePort
    adminUser: admin
    AdminPassword: password
    InstallPlugins:
      - kubernetes:latest
      - workflow-job:latest
      - workflow-aggregator:latest
      - credentials-binding:latest
      - git:latest
    CustomConfigMap: true
    NodeSelector: {}
  Agent:
    Image: jenkins/jnlp-slave
    ImageTag: alpine
    AlwaysPullImage: true
    NodeSelector: {}
  Persistence:
    Enabled: true
    StorageClass: standard

docker-registry:
  enabled: true
  image:
    repository: registry
    tag: 2.6.2
  service:
    type: NodePort
  persistence:
    enabled: true
    storageClass: standard

sonatype-nexus:
  enabled: true
  image:
    repository: cavemandaveman/nexus
    tag: 3.10.0-04
  service:
    type: NodePort
  persistence:
    enabled: true
    storageClass: standard

ingress:
  jenkins:
    enabled: true
    host: jenkins.apps.nalbam.com
    port: 80
