jenkins:
  enabled: true
  Master:
    Image: jenkins/jenkins
    ImageTag: alpine
    AdminUser: admin
    AdminPassword: password
    ServiceType: NodePort
    InstallPlugins:
      - git:latest
      - kubernetes:latest
      - workflow-job:latest
      - workflow-aggregator:latest
      - credentials-binding:latest
    CustomConfigMap: true
  Agent:
    Image: jenkins/jnlp-slave
    ImageTag: alpine
    AlwaysPullImage: true
  Persistence:
    Enabled: true
    StorageClass: standard

sonatype-nexus:
  enabled: true
  image:
    repository: cavemandaveman/nexus
    tag: 3.10.0-04
  service:
    type: NodePort
  docker:
    enabled: true
    port: 5000
    host: docker.apps.nalbam.com
  ingress:
    enabled: true
    hosts:
      - nexus.apps.nalbam.com
    annotations:
      - kubernetes.io/ingress.class: nginx
  persistence:
    enabled: true
    storageClass: standard

ingress:
  jenkins:
    enabled: true
    host: jenkins.apps.nalbam.com
    port: 8080
    annotations:
      - kubernetes.io/ingress.class: nginx
