# ------------------- PersistentVolume ------------------- #

kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-pv-001
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/001"
  persistentVolumeReclaimPolicy: Delete

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-pv-002
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/002"
  persistentVolumeReclaimPolicy: Delete

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-pv-003
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/003"
  persistentVolumeReclaimPolicy: Delete
