# ------------------- PersistentVolume ------------------- #

kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-pv-001
  annotations:
    pv.beta.kubernetes.io/gid: "1000"
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/001"
  persistentVolumeReclaimPolicy: Recycle

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-pv-002
  annotations:
    pv.beta.kubernetes.io/gid: "1000"
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/002"
  persistentVolumeReclaimPolicy: Recycle

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-pv-003
  annotations:
    pv.beta.kubernetes.io/gid: "1000"
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/003"
  persistentVolumeReclaimPolicy: Recycle

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-pv-004
  annotations:
    pv.beta.kubernetes.io/gid: "1000"
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/004"
  persistentVolumeReclaimPolicy: Recycle

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-pv-005
  annotations:
    pv.beta.kubernetes.io/gid: "1000"
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/005"
  persistentVolumeReclaimPolicy: Recycle
