# ------------------- PersistentVolume ------------------- #

kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-pv-001
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/001"
  persistentVolumeReclaimPolicy: Delete

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-pv-002
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/002"
  persistentVolumeReclaimPolicy: Delete

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-pv-003
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/003"
  persistentVolumeReclaimPolicy: Delete

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-pv-004
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/004"
  persistentVolumeReclaimPolicy: Delete

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-pv-005
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/005"
  persistentVolumeReclaimPolicy: Delete
