# ------------------- PersistentVolumeClaim ------------------- #

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-home
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-maven-repo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
