apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-delete-jobs
  labels:
    app: {{ template "fullname" . }}
    component: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        component: {{ .Release.Name }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      restartPolicy: OnFailure
      volumes:
      - name: kubectl
        hostPath:
          path: /usr/bin/kubectl
      containers:
      - name: post-install-job
        image: "lachlanevenson/k8s-kubectl:latest"
        volumeMounts:
        - name: kubectl
          mountPath: /kubectl
        command:
        - sh
        - -c
        - 'kubectl delete job --namespace {{ .Release.Namespace }} -l app={{ template "fullname" . }}'
