
image: gitlab/gitlab-ce:9.4.1-ce.0

externalUrl: http://gitlab.apps.nalbam.com

#gitlabRootPassword: ""

serviceType: NodePort

## Ingress configuration options
##
ingress:
  enabled: true
  url: gitlab.apps.nalbam.com

## Configure external service ports
## ref: http://kubernetes.io/docs/user-guide/services/
sshPort: 22
httpPort: 80
httpsPort: 443
## livenessPort Port of liveness probe endpoint
livenessPort: http
## readinessPort Port of readiness probe endpoint
readinessPort: http

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
## ref: https://docs.gitlab.com/ce/install/requirements.html#storage
##
persistence:
  ## This volume persists generated configuration files, keys, and certs.
  gitlabEtc:
    enabled: true
    size: 1Gi
    storageClass: standard
    accessMode: ReadWriteOnce
  ## This volume is used to store git data and other project files.
  gitlabData:
    enabled: true
    size: 10Gi
    storageClass: standard
    accessMode: ReadWriteOnce
