# ------------------- Deployment ------------------- #

kind: Deployment
apiVersion: apps/v1
metadata:
  name: sample-node
  namespace: default
  labels:
    app: sample-node
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: sample-node
  template:
    metadata:
      labels:
        k8s-app: sample-node
    spec:
      containers:
      - name: sample-node
        image: nalbam/sample-node:alpine
        ports:
        - containerPort: 3000
          protocol: TCP

---
# ------------------- HorizontalPodAutoscaler ------------------- #

kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: sample-node
  namespace: default
  labels:
    app: sample-node
spec:
  scaleTargetRef:
    kind: Deployment
    name: sample-node
    apiVersion: apps/v1beta1
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

---
# ------------------- Service ------------------- #

kind: Service
apiVersion: v1
metadata:
  name: sample-node
  namespace: default
  labels:
    app: sample-node
    dns: route53
  annotations:
    domainName: "sample-node.apps.nalbam.com"
    #service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    #service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "{{SSL_CERT_ARN}}"
    #service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 3000
    - name: https
      port: 443
      targetPort: 3000
  selector:
    k8s-app: sample-node

---
# ------------------- Ingress ------------------- #

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sample-node
  namespace: default
  labels:
    app: sample-node
spec:
  rules:
  - host: sample-node.apps.nalbam.com
    http:
      paths:
      - path: /
        backend:
          serviceName: sample-node
          servicePort: 80
