# ------------------- Deployment ------------------- #

kind: Deployment
apiVersion: apps/v1
metadata:
  name: sample-node
  namespace: default
  labels:
    app: sample-node
spec:
  replicas: 2
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
  selector:
    matchLabels:
      k8s-app: sample-node
  template:
    metadata:
      labels:
        k8s-app: sample-node
    spec:
      containers:
      - name: sample-node
        image: nalbam/sample-node:alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 15
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"

---
# ------------------- Service ------------------- #

kind: Service
apiVersion: v1
metadata:
  name: sample-node
  namespace: default
  labels:
    app: sample-node
    dns: route53
  annotations:
    domainName: "sample-node.apps.nalbam.com"
    #service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    #service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "{{SSL_CERT_ARN}}"
    #service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 3000
    - name: https
      port: 443
      targetPort: 3000
  selector:
    k8s-app: sample-node

---
# ------------------- HorizontalPodAutoscaler ------------------- #

kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: sample-node
  namespace: default
  labels:
    app: sample-node
spec:
  scaleTargetRef:
    kind: Deployment
    name: sample-node
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 50

#apiVersion: autoscaling/v2beta1
#kind: HorizontalPodAutoscaler
#metadata:
#  name: sample-node
#  namespace: default
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: sample-node
#  minReplicas: 1
#  maxReplicas: 100
#  metrics:
#  - type: Resource
#    resource:
#      name: cpu
#      targetAverageUtilization: 50
#status:
#  observedGeneration: 1
#  lastScaleTime: <some-time>
#  currentReplicas: 1
#  desiredReplicas: 1
#  currentMetrics:
#  - type: Resource
#    resource:
#      name: cpu
#      currentAverageUtilization: 0
#      currentAverageValue: 0
