# ------------------- Deployment ------------------- #

kind: Deployment
apiVersion: apps/v1
metadata:
  name: sample-spring
  namespace: default
  labels:
    app: sample-spring
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: sample-spring
  template:
    metadata:
      labels:
        k8s-app: sample-spring
    spec:
      containers:
      - name: sample-spring
        image: nalbam/sample-spring:alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /live
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /read
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 15
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"

---
# ------------------- Service ------------------- #

kind: Service
apiVersion: v1
metadata:
  name: sample-spring
  namespace: default
  labels:
    app: sample-spring
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8080
  selector:
    k8s-app: sample-spring

---
# ------------------- Ingress ------------------- #

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sample-spring
  namespace: default
  labels:
    app: sample-spring
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: sample-spring.apps.nalbam.com
    http:
      paths:
      - path: /
        backend:
          serviceName: sample-spring
          servicePort: 80

---
# ------------------- HorizontalPodAutoscaler ------------------- #

kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: sample-spring
  namespace: default
  labels:
    app: sample-spring
spec:
  scaleTargetRef:
    kind: Deployment
    name: sample-spring
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30

#apiVersion: autoscaling/v2beta1
#kind: HorizontalPodAutoscaler
#metadata:
#  name: sample-spring
#  namespace: default
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: sample-spring
#  minReplicas: 1
#  maxReplicas: 10
#  metrics:
#  - type: Resource
#    resource:
#      name: cpu
#      targetAverageUtilization: 50
#status:
#  observedGeneration: 1
#  lastScaleTime: <some-time>
#  currentReplicas: 1
#  desiredReplicas: 1
#  currentMetrics:
#  - type: Resource
#    resource:
#      name: cpu
#      currentAverageUtilization: 0
#      currentAverageValue: 0
