# ------------------- Deployment ------------------- #

kind: Deployment
apiVersion: apps/v1
metadata:
  name: sample-spring
  namespace: default
  labels:
    app: sample-spring
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: sample-spring
  template:
    metadata:
      labels:
        k8s-app: sample-spring
    spec:
      containers:
      - name: sample-spring
        image: nalbam/sample-spring:alpine
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /live
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 30
        readnessProbe:
          httpGet:
            scheme: HTTPS
            path: /read
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 30
#        env:
#        - name: PROFILE
#          valueFrom:
#            configMapKeyRef:
#              name: sample-spring-dev
#              key: PROFILE
#        - name: SLACK_WEBHOOK
#          valueFrom:
#            configMapKeyRef:
#              name: sample-spring-dev
#              key: SLACK_WEBHOOK
#        - name: SLACK_CHANNEL
#          valueFrom:
#            configMapKeyRef:
#              name: sample-spring-dev
#              key: SLACK_CHANNEL

---
# ------------------- Service ------------------- #

kind: Service
apiVersion: v1
metadata:
  name: sample-spring
  namespace: default
  labels:
    app: sample-spring
    dns: route53
  annotations:
    domainName: "sample-spring.apps.nalbam.com"
    #service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    #service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "{{SSL_CERT_ARN}}"
    #service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8080
  selector:
    k8s-app: sample-spring

---
# ------------------- Ingress ------------------- #

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sample-spring
  namespace: default
  labels:
    app: sample-spring
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: sample-spring.apps.nalbam.com
    http:
      paths:
      - path: /
        backend:
          serviceName: sample-spring
          servicePort: 80

---
# ------------------- HorizontalPodAutoscaler ------------------- #

kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: sample-spring
  namespace: default
  labels:
    app: sample-spring
spec:
  scaleTargetRef:
    kind: Deployment
    name: sample-spring
    apiVersion: apps/v1beta1
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
