# ------------------- CronJob ------------------- #

kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: docker-clean
spec:
  schedule: "* 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: docker-clean
            image: nalbam/builder:alpine
            args:
            - sh
            - -C
            - 'docker rmi -f $(docker images -q)'
          restartPolicy: OnFailure
