# ------------------- CronJob ------------------- #

kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: docker-clean
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: docker-clean
            image: nalbam/builder:alpine
            command:
            - sh
            - -C
            - "docker rmi -f $(docker images | grep ' <none> ' | awk '{print $3}')"
          restartPolicy: OnFailure
