# ------------------- CronJob ------------------- #
---

kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: docker-clean-rm-job
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: docker-clean-rm-job
            image: nalbam/builder:alpine
            imagePullPolicy: Always
            command:
            - docker ps -a | awk '/Exited|Dead/ {print $1}' | xargs --no-run-if-empty docker rm
          restartPolicy: OnFailure

# ------------------- CronJob ------------------- #
---

kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: docker-clean-rmi-job
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: docker-clean-rmi-job
            image: nalbam/builder:alpine
            imagePullPolicy: Always
            command:
            - docker images -q -f dangling=true | xargs --no-run-if-empty docker rmi
          restartPolicy: OnFailure

# ------------------- CronJob ------------------- #
---

kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: docker-clean-volume-job
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: docker-clean-volume-job
            image: nalbam/builder:alpine
            imagePullPolicy: Always
            command:
            - docker volume ls -q -f dangling=true | xargs --no-run-if-empty docker volume rmi
          restartPolicy: OnFailure

# docker ps -a | awk '/Exited|Dead/ {print $1}' | xargs --no-run-if-empty docker rm
# docker images -q -f dangling=true | xargs --no-run-if-empty docker rmi
# docker volume ls -q -f dangling=true | xargs --no-run-if-empty docker volume rmi

# docker rm $(docker ps -q -f status=exited)
# docker rmi $(docker images -q -f dangling=true --no-trunc)
# docker volume rm $(docker volume ls -q -f dangling=true)
