# ------------------- CronJob ------------------- #
---

kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: docker-clean-rm-job
spec:
  schedule: "10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: docker-clean
            image: nalbam/builder:alpine
            command:
            - sh
            - -C
            - "docker rm $(docker ps -q -f status=exited)"
          restartPolicy: OnFailure

# ------------------- CronJob ------------------- #
---

kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: docker-clean-rmi-job
spec:
  schedule: "20 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: docker-clean
            image: nalbam/builder:alpine
            command:
            - sh
            - -C
            - "docker rmi $(docker images -q -f dangling=true --no-trunc)"
          restartPolicy: OnFailure

# ------------------- CronJob ------------------- #
---

kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: docker-clean-volume-job
spec:
  schedule: "30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: docker-clean
            image: nalbam/builder:alpine
            command:
            - sh
            - -C
            - "docker volume rm $(docker volume ls -q -f dangling=true)"
          restartPolicy: OnFailure

# docker ps -a | awk '/Exited|Dead/ {print $1}' | xargs --no-run-if-empty docker rm
# docker images -q -f dangling=true | xargs --no-run-if-empty docker rmi

# docker rm $(docker ps -q -f status=exited)
# docker rmi $(docker images -q -f dangling=true --no-trunc)
# docker volume rm $(docker volume ls -q -f dangling=true)
