{{ if .Values.jenkins.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-create-run-command
  labels:
    app: {{ template "fullname" . }}
    component: pipeline
  annotations:
    "helm.sh/hook": post-install
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        component: pipeline
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      restartPolicy: OnFailure
      volumes:
      - name: jenkins-jobs
        configMap:
          name: {{ .Release.Name }}-jenkins-jobs
      containers:
      - name: post-install-job
        image: "python:alpine3.6"
        command:
        - curl
        - -X
        - POST
        - -H
        - "Content-Type: application/xml"
        - --retry
        - "20"
        - --retry-delay
        - "10"
        - --max-time
        - "3"
        - --data-binary
        - "@/jobs/run-command.xml"
        - "http://{{ .Release.Name }}-jenkins:8080/createItem?name=run-command"
        volumeMounts:
        - name: jenkins-jobs
          mountPath: /jobs
{{- end }}
